<a href="https://colab.research.google.com/github/Harsh04i/Urine-Test_exp2/blob/main/cleaned_dataseturineanalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving urinalysis_tests.csv to urinalysis_tests.csv

In [4]:
import pandas as pd

df = pd.read_csv("urinalysis_tests.csv")
df.head()

,Unnamed: 0,Age,Gender,Color,Transparency,Glucose,Protein,pH,Specific Gravity,WBC,RBC,Epithelial Cells,Mucous Threads,Amorphous Urates,Bacteria,Diagnosis
0,0,76.0,FEMALE,LIGHT YELLOW,CLEAR,NEGATIVE,NEGATIVE,5.0,1.010,1-3,0-2,OCCASIONAL,RARE,NONE SEEN,OCCASIONAL,NEGATIVE
1,1,9.0,MALE,DARK YELLOW,SLIGHTLY HAZY,NEGATIVE,1+,5.0,1.030,1-3,0-2,RARE,FEW,FEW,MODERATE,NEGATIVE
2,2,12.0,MALE,LIGHT YELLOW,SLIGHTLY HAZY,NEGATIVE,TRACE,5.0,1.030,0-3,0-2,RARE,FEW,MODERATE,RARE,NEGATIVE
3,3,77.0,MALE,BROWN,CLOUDY,NEGATIVE,1+,6.0,1.020,5-8,LOADED,RARE,RARE,NONE SEEN,FEW,NEGATIVE
4,4,29.0,FEMALE,YELLOW,HAZY,NEGATIVE,TRACE,6.0,1.025,1-4,0-2,RARE,RARE,NONE SEEN,FEW,NEGATIVE

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1436 non-null   int64
 1   Age               1436 non-null   float64
 2   Gender            1436 non-null   object
 3   Color             1435 non-null   object
 4   Transparency      1436 non-null   object
 5   Glucose           1436 non-null   object
 6   Protein           1436 non-null   object
 7   pH                1436 non-null   float64
 8   Specific Gravity  1436 non-null   float64
 9   WBC               1436 non-null   object
 10  RBC               1436 non-null   object
 11  Epithelial Cells  1436 non-null   object
 12  Mucous Threads    1436 non-null   object
 13  Amorphous Urates  1436 non-null   object
 14  Bacteria          1436 non-null   object
 15  Diagnosis         1436 non-null   object
dtypes: float64(3), int64(1), object(12)
memory usage: 179.6+ KB

In [6]:
df.describe()

        Unnamed: 0          Age           pH  Specific Gravity
count  1436.000000  1436.000000  1436.000000       1436.000000
mean    717.500000    27.207521     6.052925          1.015850
std     414.681806    23.460032     0.598475          0.007285
min       0.000000     0.010000     5.000000          1.005000
25%     358.750000     6.000000     6.000000          1.010000
50%     717.500000    23.000000     6.000000          1.015000
75%    1076.250000    45.000000     6.500000          1.020000
max    1435.000000    92.000000     8.000000          1.030000

In [7]:
df.shape

(1436, 16)

In [8]:
df.isnull().sum()

Unnamed: 0          0
Age                 0
Gender              0
Color               1
Transparency        0
Glucose             0
Protein             0
pH                  0
Specific Gravity    0
WBC                 0
RBC                 0
Epithelial Cells    0
Mucous Threads      0
Amorphous Urates    0
Bacteria            0
Diagnosis           0
dtype: int64

In [9]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df = df.drop_duplicates()

In [12]:
df.dtypes

Unnamed: 0            int64
Age                 float64
Gender               object
Color                object
Transparency         object
Glucose              object
Protein              object
pH                  float64
Specific Gravity    float64
WBC                  object
RBC                  object
Epithelial Cells     object
Mucous Threads       object
Amorphous Urates     object
Bacteria             object
Diagnosis            object
dtype: object

In [14]:
df.to_csv("cleaned_dataset.csv", index=False)